apiVersion: apps/v1
kind: Deployment
metadata:
  name: ensemble
  namespace: $NAMESPACE
  labels:
    app: ensemble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ensemble
  template:
    metadata:
      labels:
        app: ensemble
    spec:
      containers:
        - name: ensemble
          image: $DOCKER_ORG/$DOCKER_IMAGE:$COMMIT_SHA1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: REDIS_URL
              value: redis://redis-master:6379   
          ports:
            - containerPort: 3000
              name: http
