apiVersion: apps/v1
kind: Deployment
metadata:
  name: ensemble
  namespace: $NAMESPACE
  labels:
    app: ensemble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ensemble
  template:
    metadata:
      labels:
        app: ensemble
    spec:
      containers:
        - name: ensemble
          image: $DOCKER_ORG/$DOCKER_IMAGE:$COMMIT_SHA1
          ports:
            - containerPort: 3000
              name: http
