apiVersion: v1
kind: Service
metadata:
  name: ensemble
  namespace: $NAMESPACE
  labels:
    app: ensemble
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      name: http
  selector:
    app: ensemble
