components:
  schemas:
    ModelThread:
      description: ""
      properties:
        model_id:
          description: The Model id (optional. Set to null to run all)
          type: string
        thread_id:
          description: The Modeling thread id
          type: string
      required:
        - thread_id
      type: object
    NewModelThread:
      description: ""
      properties:
        problem_statement:
          $ref: '#/components/schemas/ProblemStatement'
        task:
          $ref: '#/components/schemas/Task'
        thread:
          $ref: '#/components/schemas/Thread'
      required:
        - problem_statement
        - task
        - thread
      type: object
    ProblemStatement:
      description: A Problem Statement definition
      properties:
        id:
          description: The id of the problem statement (leave empty if creating a new problem statement)
          type: string
        name:
          description: The name of the problem statement
          type: string
        regionid:
          description: The top level region id of the problem statement (example south_sudan, ethiopia)
          type: string
        time_period:
          $ref: '#/components/schemas/TimePeriod'
      type: object
    Task:
      description: A Task definition
      properties:
        id:
          description: The id of the task (leave empty if creating a new task)
          type: string
        indicatorid:
          description: 'The SVO label for the indicator/response (link to list upcoming). Example: grain~dry__mass-per-area_yield'
          type: string
        interventionid:
          description: 'The SVO label for the intervention (if any). Example: crop__planting_start_time'
          type: string
        name:
          description: The name of the task
          type: string
        regionid:
          description: The specific region id for the task (browse https://dev.mint.isi.edu/ethiopia/regions to get the ids)
          type: string
        time_period:
          $ref: '#/components/schemas/TimePeriod'
      type: object
    Thread:
      description: A Thread definition
      properties:
        datasets:
          description: 'A map of input name and dataset ids. Example { cycles_weather_soil: ac34f01b-1484-4403-98ea-3a380838cab1 }. To browse the datasets, go here: http://localhost:8080/ethiopia/datasets/browse'
          type: object
        modelid:
          description: 'The model id to use (browse here: https://dev.mint.isi.edu/ethiopia/models/explore. Example: cycles-0.10.2-alpha-collection-oromia)'
          type: string
        name:
          description: The name of the thread (optional)
          type: string
        parameters:
          description: 'A map of parameter name and parameter values. Example: { start_planting_day: [100, 107, 114] }'
          type: object
      type: object
    TimePeriod:
      description: A time period
      properties:
        from:
          description: From date YYYY-MM-DD format
          type: string
        to:
          description: to date YYYY-MM-DD format
          type: string
      type: object
info:
  title: Ensemble Manager API
  version: 3.0.0
openapi: 3.0.0
paths: {}
servers:
  - url: http://localhost:3000/v1
  - url: https://ensemble.mint.isi.edu/v1
