#!/bin/bash
set -ex
COMMIT=${TRAVIS_COMMIT::6}
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#build and push
docker build -t $DOCKER_ORG/$DOCKER_IMAGE:$COMMIT .
docker push $DOCKER_ORG/$DOCKER_IMAGE:$COMMIT
